plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'com.google.firebase.crashlytics'
    id 'com.google.firebase.firebase-perf'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.edxavier.vueloseaai'
    compileSdk 37

    defaultConfig {
        applicationId "com.edxavier.vueloseaai"
        minSdk 24
        targetSdk 37
        versionCode 41
        versionName "3.2.3-2026.07-ve"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.11.0'
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation "androidx.compose.ui:ui:1.11.4"
    implementation "androidx.compose.ui:ui-tooling-preview:1.11.4"
    implementation 'androidx.compose.material3:material3:1.4.0'
    implementation "androidx.compose.material:material-icons-extended:1.7.8"
    implementation "androidx.navigation:navigation-compose:2.9.8"
    implementation 'androidx.lifecycle:lifecycle-process:2.11.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.11.4"
    debugImplementation "androidx.compose.ui:ui-tooling:1.11.4"
    debugImplementation "androidx.compose.ui:ui-test-manifest:1.11.4"

    implementation 'org.jsoup:jsoup:1.22.2'
    implementation("io.coil-kt:coil-compose:2.7.0")
    implementation("androidx.core:core-splashscreen:1.2.0")

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:34.15.0')
    implementation 'com.google.firebase:firebase-crashlytics-ktx:19.4.4'
    implementation 'com.google.firebase:firebase-analytics-ktx:22.5.0'
    implementation 'com.google.firebase:firebase-perf-ktx:21.0.5'
    implementation 'com.google.firebase:firebase-config-ktx:22.1.2'

    implementation "androidx.window:window:1.5.1"
    implementation 'com.google.android.gms:play-services-ads:25.4.0'
    implementation 'com.google.ads.mediation:facebook:6.18.0.0'
}
